name = "m365-doc-monitor"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# This is crucial for Pages projects
pages_build_output_dir = ".vercel/output/static"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "m365-doc-monitor"
database_id = "b795afec-8ae1-4d9a-895b-22e2bad8eb95"

# KV Namespace binding
[[kv_namespaces]]
binding = "DOC_MONITOR_CACHE"
id = "0c6484af5a3545bc91747086a4e614b0"

# Environment variables
[vars]
GITHUB_PAT = ""

# Preview environment
[env.preview.vars]
GITHUB_PAT = ""

[[env.preview.d1_databases]]
binding = "DB"
database_name = "m365-doc-monitor"
database_id = "b795afec-8ae1-4d9a-895b-22e2bad8eb95"

[[env.preview.kv_namespaces]]
binding = "DOC_MONITOR_CACHE"
id = "0c6484af5a3545bc91747086a4e614b0"

# Production environment
[env.production.vars]
GITHUB_PAT = ""

[[env.production.d1_databases]]
binding = "DB"
database_name = "m365-doc-monitor"
database_id = "b795afec-8ae1-4d9a-895b-22e2bad8eb95"

[[env.production.kv_namespaces]]
binding = "DOC_MONITOR_CACHE"
id = "0c6484af5a3545bc91747086a4e614b0"
